services:
  server:
    image: sketchy-server:0.4.0
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./.env
    deploy:
      update_config:
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=head-proxy"
        - "traefik.swarm.network=proxy_net"
        - "traefik.http.routers.skserver.rule=Host(`skserver.rshn.cloud`)"
        - "traefik.http.routers.skserver.entrypoints=websecure"
        - "traefik.http.routers.skserver.tls=true"
        - "traefik.http.routers.skserver.tls.certresolver=le"
        - "traefik.http.services.skserver.loadbalancer.server.port=3000"
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
